# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.TextField()),
                ('entity_type', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='api', to='api.Address')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
